"""empty message

Revision ID: 50713ec073d1
Revises: 
Create Date: 2024-06-11 12:09:23.089512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50713ec073d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('de_usage_day', sa.String(length=128), nullable=False))
    op.add_column('company', sa.Column('de_usage_day', sa.String(length=128), nullable=False))
    op.add_column('house', sa.Column('de_usage_day', sa.String(length=128), nullable=False))
    op.add_column('store', sa.Column('de_usage_day', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'de_usage_day')
    op.drop_column('house', 'de_usage_day')
    op.drop_column('company', 'de_usage_day')
    op.drop_column('agency', 'de_usage_day')
    # ### end Alembic commands ###
