"""empty message

Revision ID: 8dd544e8bcc4
Revises: 
Create Date: 2024-06-10 17:27:45.460247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8dd544e8bcc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('de_name', sa.String(length=128), nullable=False),
    sa.Column('de_amperage', sa.String(length=128), nullable=False),
    sa.Column('de_wattage', sa.String(length=128), nullable=False),
    sa.Column('de_usage_time', sa.String(length=128), nullable=False),
    sa.Column('de_uid', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('de_name', sa.String(length=128), nullable=False),
    sa.Column('de_amperage', sa.String(length=128), nullable=False),
    sa.Column('de_wattage', sa.String(length=128), nullable=False),
    sa.Column('de_usage_time', sa.String(length=128), nullable=False),
    sa.Column('de_uid', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('de_name', sa.String(length=128), nullable=False),
    sa.Column('de_amperage', sa.String(length=128), nullable=False),
    sa.Column('de_wattage', sa.String(length=128), nullable=False),
    sa.Column('de_usage_time', sa.String(length=128), nullable=False),
    sa.Column('de_uid', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('de_name', sa.String(length=128), nullable=False),
    sa.Column('de_amperage', sa.String(length=128), nullable=False),
    sa.Column('de_wattage', sa.String(length=128), nullable=False),
    sa.Column('de_usage_time', sa.String(length=128), nullable=False),
    sa.Column('de_uid', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('property')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('property', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('de_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('de_amperage', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('de_wattage', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('de_usage_time', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('de_uid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('creation_date', mysql.DATETIME(), nullable=False),
    sa.Column('update_date', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('store')
    op.drop_table('house')
    op.drop_table('company')
    op.drop_table('agency')
    # ### end Alembic commands ###
