"""empty message

Revision ID: 93e459f84630
Revises: 
Create Date: 2024-06-12 12:24:46.910046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e459f84630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('de_name', sa.String(length=128), nullable=False),
    sa.Column('de_amperage', sa.String(length=128), nullable=False),
    sa.Column('de_wattage', sa.String(length=128), nullable=False),
    sa.Column('de_usage_time', sa.String(length=128), nullable=False),
    sa.Column('de_usage_day', sa.String(length=128), nullable=False),
    sa.Column('de_uid', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('de_name', sa.String(length=128), nullable=False),
    sa.Column('de_amperage', sa.String(length=128), nullable=False),
    sa.Column('de_wattage', sa.String(length=128), nullable=False),
    sa.Column('de_usage_time', sa.String(length=128), nullable=False),
    sa.Column('de_usage_day', sa.String(length=128), nullable=False),
    sa.Column('de_uid', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('de_name', sa.String(length=128), nullable=False),
    sa.Column('de_amperage', sa.String(length=128), nullable=False),
    sa.Column('de_wattage', sa.String(length=128), nullable=False),
    sa.Column('de_usage_time', sa.String(length=128), nullable=False),
    sa.Column('de_usage_day', sa.String(length=128), nullable=False),
    sa.Column('de_uid', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('de_name', sa.String(length=128), nullable=False),
    sa.Column('de_amperage', sa.String(length=128), nullable=False),
    sa.Column('de_wattage', sa.String(length=128), nullable=False),
    sa.Column('de_usage_time', sa.String(length=128), nullable=False),
    sa.Column('de_usage_day', sa.String(length=128), nullable=False),
    sa.Column('de_uid', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_fullname', sa.String(length=128), nullable=False),
    sa.Column('ad_username', sa.String(length=128), nullable=False),
    sa.Column('ad_mobile', sa.String(length=128), nullable=False),
    sa.Column('ad_address', sa.String(length=128), nullable=False),
    sa.Column('ad_email', sa.String(length=128), nullable=False),
    sa.Column('ad_password', sa.String(length=128), nullable=False),
    sa.Column('ad_uid', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('store')
    op.drop_table('house')
    op.drop_table('company')
    op.drop_table('agency')
    # ### end Alembic commands ###
