"""empty message

Revision ID: c23f45ef9b22
Revises: 
Create Date: 2024-06-04 19:50:52.987387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23f45ef9b22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_fullname', sa.String(length=128), nullable=False),
    sa.Column('ad_username', sa.String(length=128), nullable=False),
    sa.Column('ad_mobile', sa.String(length=128), nullable=False),
    sa.Column('ad_address', sa.String(length=128), nullable=False),
    sa.Column('ad_email', sa.String(length=128), nullable=False),
    sa.Column('ad_password', sa.String(length=128), nullable=False),
    sa.Column('ad_uid', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
